---

- name: Debug | ansible_service_mgr
  ansible.builtin.debug: var=ansible_service_mgr
- block:
    - name: install systemd configuration
      ansible.builtin.template:
        src: systemd-up1.service.j2
        # dest: /etc/systemd/system/multi-user.target.wants/up1.service
        dest: /lib/systemd/system/up1.service
        mode: '0644'
        backup: yes
      register: systemd
    - name: reload systemd
      ansible.builtin.systemd:
        daemon_reload: yes
        name: up1
      when: systemd.changed
  # when: ansible_service_mgr == 'systemd'
  when: >
    ansible_distribution_release == 'xenial' or
    (ansible_os_family == "RedHat" and ansible_distribution_major_version == '7')
- block:
    - name: Copy upstart service config
      ansible.builtin.template:
        src: upstart-up1.conf.j2
        dest: /etc/init/up1.conf
        owner: root
        group: root
        mode: '0644'
      notify:
        - restart up1
  when: ansible_distribution_release == 'trusty'

- name: enable and start up1 systemd service
  ansible.builtin.service:
    name: up1
    enabled: yes
    state: 'started'
