---

- name: Debug | ansible_service_mgr
  ansible.builtin.debug:
    var: ansible_service_mgr

- name: Install systemd configuration
  ansible.builtin.template:
    src: systemd-up1.service.j2
    # dest: /etc/systemd/system/multi-user.target.wants/up1.service
    dest: /lib/systemd/system/up1.service
    mode: '0644'
    backup: yes
  register: systemd
  notify:
    - Reload systemd
    - Restart up1

- name: Enable and start up1 systemd service
  ansible.builtin.service:
    name: up1
    enabled: yes
    state: 'started'
