---

- name: Ensure supervisor is present
  ansible.builtin.package:
    name: supervisor
    state: present
  register: pkg_result
  until: pkg_result is success

- name: Set up1 supervisor config
  ansible.builtin.template:
    src: supervisor-up1.conf.j2
    dest: "{{ supervisor_confdir }}/up1.{{ supervisor_ext }}"
    mode: '0644'
  notify:
    - Supervisor update

- name: Ensure supervisor service is enabled
  ansible.builtin.service:
    name: "{{ supervisor_service }}"
    enabled: "yes"
