---

- name: ensure up1 dependencies are present
  package: name={{ up1_pkg_deps }} state=present
  register: pkg_result
  until: pkg_result is success

- name: ensure up1 user exists
  user:
    name: "{{ up1_user }}"
    home: "{{ up1_home }}"

- name: git clone up1 repository
  git:
    repo: https://github.com/Upload/Up1
    dest: "{{ up1_working_dir }}"
    version: "{{ up1_version | default('9fc501783bb0510b67a99d36a3cdc852cef47f5d') }}"
  become: yes
  become_user: "{{ up1_user }}"

- block:
    - include: "random.yml name=api"
    - name: Set fact api key
      set_fact:
        up1_api_key: "{{ salt }}"
      no_log: true
  when: up1_api_key is not defined or not up1_api_key
- block:
    - include: "random.yml name=delete"
    - name: Set fact delete key
      set_fact:
        up1_delete_key: "{{ salt }}"
      no_log: true
  when: up1_delete_key is not defined or not up1_delete_key

- include: certificate-selfsigned.yml
  when: up1_https_enable and up1_https_selfsigned

- name: install server configuration
  template:
    src: server.conf.j2
    dest: "{{ up1_working_dir }}/server/server.conf"
    mode: '0644'
    backup: yes

- name: install client configuration
  template:
    src: client-config.js.j2
    dest: "{{ up1_working_dir }}/client/config.js"
    mode: '0644'
    backup: yes

- name: update up1 npm dependencies to fix deprecated one
  replace:
    dest: "{{ up1_working_dir }}/server/package.json"
    regexp: "{{ item.re }}"
    replace: "{{ item.rep }}"
  with_items:
    - { re: '"busboy": ".*",', rep: "\"busboy\": \"{{ up1_busboy_version | default('^0.3.1') }}\"," }
    - { re: '"express": ".*"', rep: '"express": "^4.16.4"' }
    - { re: '"request": ".*"', rep: '"request": "^2.88.0"' }
    - { re: '"tmp": ".*"', rep: '"tmp": "{{ up1_tmp_version | default(_up1_tmp_version) }}"' }

- name: Install up1 npm packages
  npm:
    path: "{{ up1_working_dir }}/server"
  become: yes
  become_user: "{{ up1_user }}"

- include: supervisor.yml
  when: up1_supervisor_service
- include: daemonize.yml
  when: not up1_supervisor_service

- include: cron.yml

- include: reverseproxy.yml
