# -*- mode: ruby -*-
# vi: set ft=ruby :

VAGRANTFILE_API_VERSION = "2"
ENV['VAGRANT_DEFAULT_PROVIDER'] = 'virtualbox'

Vagrant.configure(VAGRANTFILE_API_VERSION) do |config|
    config.vm.box = "ubuntu/jammy64"
    #config.vm.box = "generic/centos9s"

    config.vm.provision :ansible do |ansible|
       ansible.playbook = "site.yml"
       #ansible.verbose = "vvvv"
       #ansible.host_key_checking = false
       #ansible.limit = 'all'
       ansible.become = true
       ansible.extra_vars = { ansible_user: 'vagrant' }
       ansible.groups = {
          "vagrantselect" => ["vup1" ],
       }
    end

    config.vm.define "vup1" do |vup1|
        vup1.vm.hostname = "vup1"
#        vup1.vm.provider "virtualbox" do |v|
#          v.memory = 1024
#        end
    end

end
